# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33f1dc52fc4c31182b233d8a2188cdedda18463cf0c17893c227b9c506571bd3141a957ed560755ed8fd98170d0585726f8abbf5c566021563e40cda7ab4a0f4

test:
  secret_key_base: e17a1640f9b6f9c4124ebc4e5ce72709ac28f0b3e17affa72744a478cdb4a9da27a8a1e137fefab94a4a777edba01ec6df9d76c8da14441ab4b75059c40c2a6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
